### ISSUE TITLE
[CRASH] Works fine Client-Side but Crashes on Server

### ISSUE THREAD

**Issue by Camawama** [zehmaria/mingle#2] opened 2024-04-12 07:22 UTC
Minecraft: 1.20.1
Forge: 47.2.17
Fluid Interactions: 1.20.1-0.1.2

Crash Report:
[crash-2024-04-12_07.18.41-server.txt](https://github.com/zehmaria/fluidactions/files/14955266/crash-2024-04-12_07.18.41-server.txt)

Latest Logs:
[latest.log](https://github.com/zehmaria/fluidactions/files/14955273/latest.log)

**Comment by Camawama** [comment] 2024-04-12 07:31
**java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER**

**Comment by zehmaria** [comment] 2024-04-12 19:18
I think I see what the issue is, but I am gonna test on a server first before uploading the fix. Thanks for the heads up.

**Comment by zehmaria** [comment] 2024-04-12 23:36
This has been fixed in 0.1.3, the new version should be approved on curseforge soon, and it is already up on modrinth. Again, thanks for the report, have fun.

**Closed as completed by zehmaria** 2024-04-12 23:36 UTC
